name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-13
    strategy:
      matrix:
        destination:
          - "platform=macOS"

    steps:
      - uses: actions/checkout@v3
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme TextViewPlus -destination "${{ matrix.destination }}" test | xcpretty
